version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Giao diện web Portainer
      - "8000:8000"  # API Portainer (tuỳ chọn)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Kết nối Docker với Portainer
      - portainer_data:/data  # Lưu trữ dữ liệu Portainer
volumes:
  portainer_data:
